Scope -> Extension.Scope
CareEvolution/OrchestrateSDK pull request #19
Opened 2023-09-27 18:40 UTC by jeremytwfortune

## Description of Changes

The current version incorrectly tries to filter the FHIR endpoints by scope using `scope` when it should be `extension.scope`.

## Security

**REMINDER: All file contents are public.**

- [x] I have ensured no secure credentials or sensitive information remain in code, metadata, comments, etc. Of particular note: No temporary testing changes committed such as API base URLs, access tokens, print/log statements, etc.
- [x] My changes do not introduce any security risks, or any such risks have been properly mitigated.

These parameters are manually created in the SDK, so there are no changes to user inputs or outputs.

## Reviewers

- [x] I have assigned the appropriate reviewer(s).

2023-09-27 18:49 UTC, scottfavre requested changes

2023-09-27 18:49 UTC, scottfavre commented on typescript/tests/api.test.ts
> +    expect(result.entry?.length).toBeLessThan(10000);
should this be `<= 10000`? if the limit is 10k, you might get 10k.

2023-09-27 18:49 UTC, scottfavre commented on python/tests/test_api.py
> +    assert len(result["entry"]) < 10000
should be `<=`

2023-09-29 12:43 UTC, jeremytwfortune commented on python/tests/test_api.py
> +    assert len(result["entry"]) < 10000
See other comments.

2023-09-29 13:36 UTC, scottfavre approved these changes

2023-09-29 13:38 UTC, merged